### ISSUE TITLE
[BUG] MacBook3,1 can't see USB boot drive(s)

### ISSUE THREAD

**Issue by RedBearAK** [rmc-team/osx-patcher#11]
I have no idea how this could possibly have been caused by osx-patcher, but I've experienced a strange problem where a MacBook3,1 was suddenly unable to "see" certain USB bootable media at the Option-key boot picker screen. I notice there is a seemingly related closed bug report but the original post has been removed so I can't tell what that person's description of the situation was. 

This problem is not something I've ever seen happen on any other Mac, and I've messed with quite a few over the past 20 years. Some USB bootable drives just simply wouldn't appear on the boot picker screen, while others would, so it doesn't appear to be a problem with the USB port(s). Also tested with several different Linux ISO images, and I think a Lion installer (which should be natively compatible with the MacBook3,1). Ultimately this issue kept me from being able to use the osx-patcher installer from USB. 

Fortunately I remembered I had a FireWire Compact Flash card reader, and was able to put a patched installer on a CF card and boot from that. All the different Linux ISOs as mentioned above would appear and be bootable using the FireWire CF card reader. 

It's strongly stated in the other thread that this couldn't possibly be caused by osx-patcher, but it's a really unusual phenomenon and there are now two of us that have experienced it. 

I can't say with any certainty that it was caused by attempting to boot from a osx-patcher patched installer USB, or placing a patched installer USB in that MacBook3,1, but I can say that I don't remember booting from any kind of USB install media being a problem before that, and then suddenly this problem existed and started driving me nuts. Almost as if the osx-patcher media somehow caused it. The only reason I'm not really that upset about it is because the FireWire CF card reader with a good CF card turned out to be super fast and convenient compared to using USB on a 2.0 port. 

This phenomenon behaves the same regardless of which USB port is used, or whether the USB media is in the port when the machine is turned on, or inserted while the boot picker screen is already up. It is clearly unlikely to be a USB port issue. The USB ports work fine when booted into Linux or El Capitan. I've tried many different USB flash drives as well. Something seems to have somehow affected the firmware of the MacBook3,1 in such a way that it simply can no longer see certain bootable USB media. Always. But it does see some. Always. Meanwhile, FireWire bootable media is unaffected.

**Comment by julian-fairfax** [comment]
Sorry for not responding to this sooner. This is the last time I'm going to address this: OS X Patcher cannot modify your firmware and no software modification can cause this. OS X Patcher only creates a patched installer volume that you can then use to install an official version of OS X, which also cannot modify your firmware since it doesn't support your Mac and doesn't include firmware updates for it.
