### ISSUE TITLE
El Capitan Installer boots up, but no install screen pops up

### ISSUE THREAD

**Issue by schoelli** [rmc-team/osx-patcher#12]
**Describe the bug**
Bootup from El Capitan USB Installer Stick on a iMac 6,1 doesn't show the language select screen, so no installation can be done. The utility tools from the top menu are working correctly, but even if you close those apps, the install screen won't show up

**To Reproduce**
Created bootable usb stick with release release-174751-300720 via terminal on iMac 6,1 and Install OS X El Capitan.app
Terminal said everything is fine
Booting up from USB Stick works as expected
No Install Screen (Tools working)

**Screenshots/logs**
If applicable, add screenshots and/or logs to help explain your problem.

**Mac (please complete the following information):**
iMac 6,1 OSX 10.7.5
OSX Patcher Script 1.1.3 with
OSX El Capitan.app 1.7.44 10.10.4

**Additional context**
Installing 10.9 via script was flawless, booting up perfectly, installing was fine, installing 10.10 couldn't load the usb stick (some kind of screentext and automatic rebooting on the loading screen) 10.11 installer boots up but no install screen.

**Comment by schoelli** [comment]
![3410C004-DAED-41B0-A41D-B00F7C817E1D_1_102_a](https://user-images.githubusercontent.com/318472/89623275-9e406080-d894-11ea-95d4-7aabab67a315.jpeg)
![C8C9269D-5192-4A06-8CA3-95ED9A130458_1_105_c](https://user-images.githubusercontent.com/318472/89623284-a3051480-d894-11ea-950a-afc18feb7e4b.jpeg)

**Comment by julian-fairfax** [comment]
OS X Patcher was developed to be used with the latest installer applications. I highly recommend you download a 10.11.5 installer and try again.

**Comment by schoelli** [comment]
> OS X Patcher was developed to be used with the latest installer applications. I highly recommend you download a 10.11.5 installer and try again.

You are completely right, i used an old version (1.7.44).
Tried to download the newest version via macOs Downloader Tool, the version 1.7.50 works as expected!

One small question after install: The graphics are extremely sluggish on an iMac 6,1 with GeForce 7600 GT (same with Yosemite). Will there be any way to enhance the graphic card driver. At the moment the operating system it isn't very "usable"

**Comment by julian-fairfax** [comment]
Unfortunately there's not much I can do to fix it. The computer is very old and is running a much newer OS. I'm sorry that isn't working for you. If you want a more technical explanation: The Intel and Nvidia graphics drivers were written before 64-bit support was common. El Capitan has a 64-bit kernel and no longer supports loading 32-bit drivers.
