### ISSUE TITLE
Install El Capitan on MacBook 2,1

### ISSUE THREAD

**Issue by mapomme1108** [rmc-team/osx-patcher#19]
Hello,

First, thank you for your work,

I have created an El Capitan USB installer with OS X Patcher.
I have installed El Capitan on a MacBook 2,1 but when I reboot on the USB, open Terminal
and run "patch", nothing happens.

How can I fix this issue?

Thank you for your help

**Comment by julian-fairfax** [comment]
By nothing happens, what do you mean? Does it say command not found? Does it run but not work? I need a more specific description of the result you're getting.

**Comment by mapomme1108** [comment]
Hello,
After installing El Capitan on the hard drive, I boot from the El Capitan USB Installer, I open terminal and type "patch" : by nothing happens, I mean that it does not run and there is no message at all.
Should I type "patch" in a specific folder?

**Comment by julian-fairfax** [comment]
Can you run ls / from within the installer and show me what comes up?

**Comment by julian-fairfax** [comment]
Do you have any new information that might help find out the issue?
