### ISSUE TITLE
I can't start the volume with OS X 10.8.5

### ISSUE THREAD

**Issue by Nermas** [rmc-team/osx-patcher#20]
I'm trying to install OS X 10.8.5 on a Macbook 4.1 (early 2008), now on the Mac 2 operating systems: Mac OS X 10.5.8, Mac os 10.7.5, installed on one volume installer OS, on the second Mac OS 10.8.5. I did everything according to the instructions, but after starting the volume with OS X 10.8.5 for some reason, another volume starts, with OS X 10.5.8. I can't start the volume with OS X 10.8.5

**Comment by julian-fairfax** [comment]
Did you make sure to run the patch command after installing?

**Comment by Nermas** [comment]
I tried installing Mavericks. An installation error occurred...

**Comment by Nermas** [comment]
The fact is that after installation, the computer automatically restarts, after which it shows a crossed-out circle. After restarting, it starts another volume that the working system is on.

**Comment by julian-fairfax** [comment]
You need to run the patch command after installing otherwise it will not boot. This is specified in the readme.

**Comment by Nermas** [comment]
> Вам нужно запустить команду patch после установки, иначе она не загрузится. Это указано в readme.

But the computer automatically restarts after installation...

**Comment by julian-fairfax** [comment]
Then restart back to the installer and run the command

**Comment by Nermas** [comment]
> Затем перезапустите программу установки и выполните команду

That's what I do..

**Comment by Nermas** [comment]
And the volume on which to boot the system should be called "Macintosh HD"? I read about it somewhere.

**Comment by julian-fairfax** [comment]
That depends on what you decided called it. But before you can boot from the system volume, you need to boot from the installer usb and run the patch command in the terminal app as is described here: https://github.com/rmc-team/osx-patcher#patch-the-os

**Comment by Nermas** [comment]
> Это зависит от того, как вы решили это назвать. Но прежде чем вы сможете загрузиться с системного тома, вам нужно загрузиться с usb установщика и запустить команду patch в терминальном приложении, как описано здесь: https://github.com/rmc-team/osx-patcher#patch-the-os

I was running patch. But after that, another volume was still running.

**Comment by Nermas** [comment]
> Это зависит от того, как вы решили это назвать. Но прежде чем вы сможете загрузиться с системного тома, вам нужно загрузиться с usb установщика и запустить команду patch в терминальном приложении, как описано здесь: https://github.com/rmc-team/osx-patcher#patch-the-os

I was running patch. But it still runs on a different volume.

**Comment by Nermas** [comment]
Is it necessary to start from USB? I split the disk, on one the installer, on the other the future system.

**Comment by julian-fairfax** [comment]
> Is it necessary to start from USB? I split the disk, on one the installer, on the other the future system.

No, you can put the installer and the system on the same disk

**Comment by julian-fairfax** [comment]
> > Это зависит от того, как вы решили это назвать. Но прежде чем вы сможете загрузиться с системного тома, вам нужно загрузиться с usb установщика и запустить команду patch в терминальном приложении, как описано здесь: https://github.com/rmc-team/osx-patcher#patch-the-os
> 
> I was running patch. But it still runs on a different volume.

Did you select your system disk as the disk to be patched?

**Comment by Nermas** [comment]
> > > It depends on what you decide to call it. But before you can get out from the system-th, you need to get from usb installer and run the patch command in the terminal application, as described here: https://github.com/rmc-team/osx-patcher#patch-the-os
> > 
> > 
> > Я бегал по патчу. Но он все еще работает на другом томе.
> 
> Вы выбрали системный диск в качестве диска для исправления?

Let me explain in more detail.
 I split the disk where I make 2 two volumes. Volume 1 is the installer, volume 2 is the system. After that, I run the installer with a pre-prepared OS X. I install the system, after installation, the laptop restarts. The system does not start. After rebooting, I go to the installation volume and do a patch. After that, I start the system and another disk starts up. When booting where the apple is, the startup starts flickering out of the apple and the crossed-out circle, but still starts another volume.. help...

**Comment by julian-fairfax** [comment]
Did the patch command show any errors when you ran it?

**Comment by Nermas** [comment]
> Did the patch command show any errors when you ran it?

No

**Comment by julian-fairfax** [comment]
Would you mind running it again and showing me a photo of what you see?

**Comment by Nermas** [comment]
I managed to install Mac OS Mavericks, everything works fine, thank you.

**Comment by julian-fairfax** [comment]
That’s good to hear. Thanks for using my tool!

Julian Fairfax
