### ISSUE TITLE
install osx dmg bug

### ISSUE THREAD

**Issue by wstroftgithub** [rmc-team/osx-patcher#21]
So I downloaded the InstallMacOSX.dmg file at https://support.apple.com/en-us/HT211683 but when i copy the path of the file it says:

> Checking installer support.
- Installer support check failed.
/ Run this tool with a supported installer.

 - OS: macOS X 10.6.8 Snow Leopard

Any fixes?

**Comment by julian-fairfax** [comment]
You need to use an installer .app file. You can download one with macOS Downloader.
