### ISSUE TITLE
Advice for wifi?

### ISSUE THREAD

**Issue by timmujapan** [rmc-team/osx-patcher#23]
Using the OS X patcher tool, I was able to get El Capitan running on my MacBook 2,1. I think that it is great that this information is being made available. amazing! thank you!!! The instructions on GitHub could be a bit more clear for the average user, for example “which one of the files is the ‘script’ file?” People with less experience applying patches, etc., will struggle with the explanations provided, I think. I should also point out that the OS X patcher did not work on my MacBook 2,1 running lion 10.7.5. I made the USB patched bootable elcapitan drive with a MacBook Pro 8,1. Including these kinds of details will help less experienced people who would nonetheless like to patch with this wonderful tool you made.

There is also the issue of the type of USB thumb drive used to create the bootable, patched El Capitan installer for an older mac. With a MacBook 2,1, not all usb drives will be detected when pressing the option key at start-up. I found that an older usb stick (USB 2.0) and formatted with the MBR partition and os extended (journaled) has the best chance of being detected by a MacBook 2,1 as a bootable drive. Ive had good luck with a bootable installer on my MacBook 2,1 with this thumb drive:

www.amazon.com
SanDisk Cruzer Blade 16GB USB 2.0 Flash Drive

One question I have:

my MacBook 2,1 was originally a MacBook 1,1 with a core duo logic board (A1181). Because some of the Logic boards for the A1181 are interchangeable, I was able to upgrade the logic board to a 2 ghz core 2 duo logic board quite easily. The only part of the board that remains from the MacBook 1,1 is the wifi card...... and wifi is not being detected in the El Capitan patched install.

previously, I triple booted this computer with windows 10 (32 bit), Ubuntu 18.04, and Lion 10.7, and there was a way to get wifi working in all of these operating systems.

Now, after installing El Capitan, I have Ubuntu 18.04, Lion 10.7, and El Capitan 10.11 triple booted each on its own partition, thanks to the wonderful OS X patcher tool.....

but no wifi in El Capitan..... my wifi card is from a MacBook 1,1, I believe.....

does anyone have advice about a kext, driver, etc. to install that could help get the wifi working in the patched El Capitan? And how to do that? Any advice would be greatly appreciated. Your patcher tool is amazing, thank you!!!

cheers!

**Comment by julian-fairfax** [comment]
> Using the OS X patcher tool, I was able to get El Capitan running on my MacBook 2,1. I think that it is great that this information is being made available. amazing! thank you!!! The instructions on GitHub could be a bit more clear for the average user, for example “which one of the files is the ‘script’ file?”

I agree the instructions/support information and stuff could be improved. Thanks for your feedback.
> People with less experience applying patches, etc., will struggle with the explanations provided, I think. I should also point out that the OS X patcher did not work on my MacBook 2,1 running lion 10.7.5. I made the USB patched bootable elcapitan drive with a MacBook Pro 8,1. Including these kinds of details will help less experienced people who would nonetheless like to patch with this wonderful tool you made.

That should've worked. But since you've got it working now it's not important.
> There is also the issue of the type of USB thumb drive used to create the bootable, patched El Capitan installer for an older mac. With a MacBook 2,1, not all usb drives will be detected when pressing the option key at start-up. I found that an older usb stick (USB 2.0) and formatted with the MBR partition and os extended (journaled) has the best chance of being detected by a MacBook 2,1 as a bootable drive. Ive had good luck with a bootable installer on my MacBook 2,1 with this thumb drive

I'm not sure what the cause of that is but try to use a USB revision that corresponds to your port, like you did.
> my MacBook 2,1 was originally a MacBook 1,1 with a core duo logic board (A1181). Because some of the Logic boards for the A1181 are interchangeable, I was able to upgrade the logic board to a 2 ghz core 2 duo logic board quite easily. The only part of the board that remains from the MacBook 1,1 is the wifi card...... and wifi is not being detected in the El Capitan patched install.

That's normal and I don't think I'm going to fix it because it's not really a supported configuration. I'd recommend you buy a MacBook2,1 AirPort card, if you can get your hands on one.
> previously, I triple booted this computer with windows 10 (32 bit), Ubuntu 18.04, and Lion 10.7, and there was a way to get wifi working in all of these operating systems.

If you let me know how you got it working then I could check if the same method would work on El Capitan.
