### ISSUE TITLE
[BUG] No Wi-Fi on Macmini1,1 10.11.6

### ISSUE THREAD

**Issue by Piipperi** [rmc-team/osx-patcher#28]
**Describe the bug**
No Wi-Fi or iPhone-USB on El Capitan, basically the only options are Ethernet, FireWire and Bluetooth PAN

**Mac (please complete the following information):**
 - OS: El Capitan 10.11.6
 - Version 10.11.6

**Additional context**

**Comment by julian-fairfax** [comment]
What device are you experiencing this issue on?

**Comment by julian-fairfax** [comment]
I see in it's a mac mini, in which case I'm sorry to inform you that this is a known issue (that will be added to the documentation for future reference) and as of date there is no solution for it. If you are able to, using Ethernet is would be the only method to get an internet connection (assuming Ethernet functionality is present. I don't have one of these machines so I can't attest to that).
