### ISSUE TITLE
[BUG] Installing El Capitan on Macbook2,1 ends up in boot loop

### ISSUE THREAD

**Issue by mkullber** [rmc-team/osx-patcher#29]
Installling El Capitan on Macbook2,1 ends up in boot loop

**To Reproduce**
1. Download and install El Capitan with these instructions using newest versions in GitHub: https://github.com/rmc-team/macos-downloader and https://github.com/rmc-team/osx-patcher (and remember to patch after installing)
2. Boot into installed El Capitan
3. El Capitan loads for a while, when progress bar hits about 60-70% the computer boots. Can't get past it

**Screenshots/logs**
In verbose boot mode this is the last thing before reboot
![macbook](https://user-images.githubusercontent.com/5870691/108857975-5563b580-75f4-11eb-8cdb-b9308d88f412.jpg)

 - OS: macOS 10.11.6

**Additional context**
Tried to fix permissions of boot volume from single user mode, didn't help:
```
fsck
mount -uw /
sudo /usr/libexec/repair_packages --repair --standard-pkgs --volume / 
```

**Comment by julian-fairfax** [comment]
When you run the patch command with the -v flag do you see any errors?

**Comment by mkullber** [comment]
Same error occurs in verbose boot and with patch -v
![IMG_20210223_170543](https://user-images.githubusercontent.com/5870691/108863377-d1143100-75f9-11eb-9b62-fb3c612345a4.jpg)

**Comment by julian-fairfax** [comment]
Does this issue also occur on Yosemite? El Capitan has some additional patches that are most likely causing this (although I'm not sure why they're not working)

**Comment by mkullber** [comment]
I found a workaround for this issue, as I won't be using Magic Mouse/Trackpad: I deleted the AppleBluetoothMultitouch extension.

**Comment by julian-fairfax** [comment]
Well that's certainly an inventive solution! If you're no longer experiencing the issue then please go ahead and close this. (Feel free to reopen it if you one day do you use a Magic Mouse/Trackpad)
