### ISSUE TITLE
[BUG] Touchpad and Keyboard not working on MacBookAir 1,1

### ISSUE THREAD

**Issue by Baboo85** [rmc-team/osx-patcher#6]
Hi, in my MacBookAir 1,1 when the system boot from the usb key prepared with this tool, touchpad and keyboard are not working.
I need to connect an USB Hub with at least 3 port for external usb mouse, keyboard and the usb bootable key.

**Comment by Baboo85** [comment]
Just to let you know, with a Yosemite 10.10 installation touchpad and keyboard are working (it's installing and it's almost 1/3 of the bar).

**Comment by julian-fairfax** [comment]
Do NOT create multipe issues before trying to fix the problem. If you have fixed it, close the issue.
