### ISSUE TITLE
[BUG] Error "OS X could not be installed on your computer" during El Capitan installation

### ISSUE THREAD

**Issue by Baboo85** [rmc-team/osx-patcher#7]
Hi, as mentioned in the title, when the installation starts, after a couple of seconds I get the error "OS X could not be installed on your computer. No eligible package".
I was trying to install El Capitan (in app format, downloaded from the App Store).
MacBook Air 1,1

**Comment by Baboo85** [comment]
Just to let you know, Yosemite 10.10 is installing (it's almost 1/3 of the bar).

**Comment by julian-fairfax** [comment]
Do NOT create multiple issues before trying to fix the problem. If you have fixed it, close the issue.
