### ISSUE TITLE
[FEATURE] Compatibility with DMG installation files

### ISSUE THREAD

**Issue by Baboo85** [rmc-team/osx-patcher#8]
Hi, it would be nice to have the compatibility with the DMG installation files, because the .APP files are difficult to find if one not have it (i.e.: I couldn't find a Yosemite.app working, I always found zip files corrupted).
Or, to have less work to do, having the .APP files downloadable from your main site.

**Comment by julian-fairfax** [comment]
You can use [macOS Downloader](https://github.com/rmc-team/macos-downloader) to download an official copy of an OS X Yosemite installer. I won't be adding support for unofficial copies of OS X to my tools.

**Comment by Baboo85** [comment]
Thanks for the hint of the macOS Downloader, but FYI the DMG files aren't "unofficial copies".
You can download for example Yosemite.dmg from the Apple Support site directly: https://support.apple.com/en-us/HT210717
Step 4.
