### ISSUE TITLE
[BUG] Couldn't boot any usb bootable key to Patch OS X after installation

### ISSUE THREAD

**Issue by Baboo85** [rmc-team/osx-patcher#9]
Hi, as the title says I just finished installing Yosemite. Now I need to boot again from the usb key to Patch OS X to be able to boot the system, but no usb key is displayed at boot holding down the alt-option key.
Just the Yosemite and the Recovery partition are displayed and I can't go further. I tried to create a new Yosemite bootable key with standard procedure, I tried to use the old Lion usb bootable key but no luck. I cannot boot anything.
Tried to reset PRAM/NVRAM and the SMC, but no luck.
Now I'm definitely stuck, cannot boot anything, cannot even go back to Lion.
I have a MacBook Air 1,1

**Comment by julian-fairfax** [comment]
You're correct about having to boot into it to patch your system. However, it's not possible for OS X Patcher to have caused a problem like this.

**Comment by Baboo85** [comment]
Why did you closed other issues? They aren't solved, I cannot install El Capitan and also touchpad and keyboard aren't working. The APP is mine downloaded from App Store.

Anyway here the problem is that absolutely no usb key that were visible at boot and bootable before, now aren't working. The old Lion or the OS X Patcher usb key created with your tool aren't even visible.
I only see the OS X system and the Recovery, but obviously aren't bootable (because they need the fix). The usb is working because I tried an usb mouse and it works.
Something changed in the UEFI bootloader? Do I need to recreate it under another Mac?

**Comment by Baboo85** [comment]
Hi, do you have any hints?

**Comment by julian-fairfax** [comment]
Sorry, I don't. But this isn't caused by any of my tools, it can't be. You check your USB sticks/ports and stuff.

**Comment by Baboo85** [comment]
The usb keys worked in that MacBook Air before using your tool. The same usb key I used to install Yosemite stopped being visible at boot after the installation.
The same Yosemite usb key is visible on boot in another MacBook Air (late 2010) with Sierra. Same for the usb key with Lion and El Capitan.
The MacBook Air where those keys are not showing at boot, has the usb port working (both usb mouse and keyboard work in the boot menu).
The APPs I'm using are originals from App Store.

So: the usb port is working, usb keys are visible in boot menu in another MacBook. And you say it's not caused by your tool?
There is definitely something in the boot modified by your tool that don't show the usb key (but MacBooks haven't an accessible BIOS/UEFI so I can't do anything, the "Command-Option-O-F" doesn't do anything).

**Comment by julian-fairfax** [comment]
I've already told you this can't be caused by any of my tools.

**Comment by Baboo85** [comment]
Seriously? Ok, now I understard. The fact that you don't even know what your tool does, explains why I have problem now.
Go f*ck yourself, you and your f*cking tool, you just killed someone's MacBook Air and you don't even want to give some help. The virus Cryptolocker on Windows did less damage.
Worst person on internet I ever met.
